[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd backend && npm ci --production=false']

[phases.build]
cmds = ['echo "No build step needed for backend"']

[start]
cmd = 'cd backend && node server.js'